---
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../output/") })
---

```{r, echo = FALSE}
knitr::opts_chunk$set (collapse=TRUE, comment="##", fig.path = "../images/", warning = FALSE)
```

```{r message=FALSE, warning=FALSE}
library (rvest)
library(httr)
library (tidyverse)
```

```{r}
url = "https://www.twbiobank.org.tw/new_web/contact.php"
res = GET (url) # use GET method to get the web response
res
```

# A quick view of the web response
```{r}
# str (res)  
# names (res)
# res$all_headers
# res$request
# res$request$headers  
# res$cookies  
# res$content
```


# Info we want is usually in "content"
```{r}
# content(res, as = "raw") # binary codes
# content(res, as = "text") # default encoding method is utf-8
```

# (1) Scrape the site addresses
```{r}
address <- res %>% 
  content (as = "text") %>% 
  read_html %>% 
  html_nodes (xpath = "//div[@class='panel address']") %>% 
  html_text %>% # turn the content into text
  as.data.frame # turn into data.frame

class (address)
str(address)
head (address) # View the site name and address info
```

# Some data cleaning
```{r}
address_df <- address %>% 
  separate (".", into = c ("city", "location"), sep = 2) %>% 
  slice (2:n()) # select 2nd to n rows

for (i in 1:nrow(address_df)){
  address_df$location[i] <- ifelse (grepl("駐站", address_df$location[i]) == FALSE, 
                                   sub ("醫院", "醫院駐站", address_df$location[i]), address_df$location[i])
}

address_df <- address_df %>% 
  mutate (site = sub ("駐站.*", "", address_df$location),
          address = sub ("^.*駐站", "", address_df$location)) %>% 
  separate ("address", into = c ("address", "building"), sep = " ") %>% 
  select (-location)

address_df$address[31] <- sub (".*)", "", address_df$address[31])

head (address_df)
dim (address_df)
```

# (2) Scrape the coordinate info
```{r}
geo <- res %>% 
  content (as = "text") %>% 
  read_html %>% 
  html_nodes (xpath = "//li[@data-geo-lat]") %>% 
  html_attrs 

#str (geo)
```

# Some data cleaning
```{r}
geo_df <- t (as.data.frame (geo, col.names = paste0("X", c(1:34)))) 
head (geo_df)
row.names (geo_df) <- NULL
```

# (3) Combine the 2 tables
```{r}
stations <- cbind (address_df, geo_df)
library (knitr); library (kableExtra)
kable (stations, format = "markdown")
```
